// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ProductService.Infrastructure
{
    public partial class DataContextModel
    {
        partial void Initialize()
        {
            var championshipModel = ChampionshipModelEntityType.Create(this);
            var eventModel = EventModelEntityType.Create(this);
            var playerModel = PlayerModelEntityType.Create(this);
            var scoreboardModel = ScoreboardModelEntityType.Create(this, playerModel);
            var rankingModel = RankingModelEntityType.Create(this, scoreboardModel);

            ChampionshipModelEntityType.CreateAnnotations(championshipModel);
            EventModelEntityType.CreateAnnotations(eventModel);
            PlayerModelEntityType.CreateAnnotations(playerModel);
            ScoreboardModelEntityType.CreateAnnotations(scoreboardModel);
            RankingModelEntityType.CreateAnnotations(rankingModel);

            AddAnnotation("ProductVersion", "6.0.6");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
